myapp/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

myapp/blog_posts/views.py
#blogposts/views 

from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import BlogPost
from myapp.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__) # register this in __Init__ py 

# Create a blog post 

@blog_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('BLog Post Created')
        print('Blog post was created')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)


# view a single post
@blog_posts.route('/<int:blog_post_id>') #make sure this is an integer 
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id) # this blog post id is not a string - we are querying for an int 
    return render_template('blog_post.html', title=blog_post.title, date=blog_post.date, post=blog_post)


# update a post 

@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()


    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html',title='Updating',form=form)




# delete post 
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index'))

myapp/core/views.py
# core/views.py 

from flask import render_template, request, Blueprint
from myapp.models import BlogPost

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', blog_posts=blog_posts)


@core.route('/info')
def info():
    return render_template('info.html')

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, BlogPost
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5) 
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

myapp/templates/account.html
{% extends "base.html" %} {% block content %}

<div>
<div align="center">
    <h1>Welcome to the page for {{current_user.username}}</h1>
</div>
</div>

<div>
<form method="POST" action="" enctype="multipart/form-data">
    <div>{{form.hidden_tag()}}</div>
    <div id="username">
    {{form.username.label(class='form-group')}}
    {{form.username(class='form-control')}}
    </div>
    <div id="email">
    {{form.email.label(class='form-group')}}
    {{form.email(class='form-control')}}
    </div>

    <div>{{form.submit(class='btn btn-primary')}}</div>
</form>
</div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="/static/favicon/favicon.png" />
    <link rel="stylesheet" href="/static/css/main.css" />
    <title>Nocturn</title>
  </head>

  <body>
    <ul class="nav">
      <li class="nav-link">
        <a href="{{url_for( 'core.index')}} ">Home</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for( 'core.info')}} ">About</a>
      </li>

      {% if current_user.is_authenticated %}
      <li class="nav-link">
        <a href="{{url_for( 'blog_posts.create_post')}} ">Create Post</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for( 'users.logout')}} ">Log Out</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for( 'users.account')}} ">Account</a>
      </li>
      {% else %}
      
      <li class="nav-link">
        <a href="{{url_for( 'users.register')}} ">Register</a>
      </li>
      <li class="nav-link">
        <a href="{{url_for( 'users.login')}} ">Log In</a>
      </li>
      {% endif %}
    </ul>

    <div class="container">{% block content %} {% endblock %}</div>
  </body>
</html>

myapp/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div>
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <br>
       <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
        <input type="submit" value="Delete">
      </form> 
     </div>
   {% endif %}
</div>
{% endblock content %}

myapp/templates/create_post.html
{% extends "base.html" %} 
{% block content %}
<div>
    <form method="POST">
        {{form.hidden_tag()}}

        <div>
            {{form.title.label(class="form-control-label")}} 
            {{form.title(class="form-control form-control-lg")}}
        </div>
        <div>
            {{form.text.label(class="form-control-label")}} 
            {{form.text(class="form-control form-control-lg")}}
        </div>
        <div>
            {{form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %} {% block content %}


<div>
    <h1>Blog</h1>
    <div class="hr"></div>
</div>
<div>
    {% for post in blog_posts.items %}
    <div>
        <div>
            <h2>
                <a href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a>
                <a href="{{url_for('users.user_posts', username=post.author.username)}}">Written by: {{post.author.username}}</a>
            </h2>
            <p>Published on: {{post.date.strftime('%Y - %m - %d')}}</p>
            <a href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">Read Blog Post</a>
        </div>
    </div>
    {% endfor %}
</div>

<nav aria-label="Page Navigation example">
    <ul>
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if blog_posts.page == page_num %}
        <li>
            <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li>
            <a href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %} {% endfor %}
    </ul>
</nav>
{% endblock %}

myapp/templates/info.html
{% extends "base.html" %} {% block content %}

<div>
    <h1>About</h1>
    <div class="hr"></div>
    <p>An app all about night vision observations and stargazing. The night comes alive with different sounds and experiences. Write about it here and encourage investing in NODs (Night Observation Devices) as a tool to enjoy all 24 hours of a day.</p>
</div>

{% endblock %}

myapp/templates/login.html
{% extends "base.html" %} {% block content %}

<form method="POST">
    {{form.hidden_tag()}} {{form.email.label}}{{form.email}}
    <br> {{form.password.label}}{{form.password}}
    <br> {{form.submit()}}

</form>
{% endblock %}

myapp/templates/nocturn_shop_items.html
{% extends "base.html" %} {% block content %}
<div class="container">
    <div class="jumbotron">
        <div align="center">
            <h1>Welcome to the page for {{user.username}}</h1>
        </div>
    </div>
    {% for post in blog_posts.items %}
    <h2>
        <a href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a>
    </h2>
    Written By: <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>

    <p class="text-muted">
        Published On: {{post.date.strftime("%y-%m-%d")}}
    </p>
    <br>
    <p>{{post.text}}</p>
    <br> {% endfor %}
</div>

<nav aria-label="Page Navigation example">
    <ul class="pagination justify-content-center">

        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %} {% endfor %}
    </ul>
</nav>


{% endblock %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}

<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.username.label}}{{form.username}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
    {{form.submit()}}
</form>
{% endblock %}

myapp/templates/user_blog_posts.html
{% extends "base.html" %} 
{% block content %}
<div>
    <div>
        <div>
            <h1>Welcome {{user.username}}</h1>
        </div>
    </div>
    {% for post in blog_posts.items %}
    <h2>
        <a href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a>
    </h2>
    Written By: <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>

    <p>
        Published On: {{post.date.strftime("%y-%m-%d")}}
    </p>
    <br>
    <p>{{post.text}}</p>
    <br> {% endfor %}
</div>

<nav aria-label="Page Navigation example">
    <ul>

        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if blog_posts.page == page_num %}
        <li>
            <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li>
            <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %} {% endfor %}
    </ul>
</nav>


{% endblock %}